// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using StudyUp;
using System;

namespace StudyUp.Migrations
{
    [DbContext(typeof(StudyUpContext))]
    partial class StudyUpContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("StudyUp.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("Name");

                    b.Property<DateTime>("StartDate");

                    b.Property<int?>("StudentId");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("StudyUp.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int?>("StudyGroupId");

                    b.HasKey("Id");

                    b.HasIndex("StudyGroupId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("StudyUp.StudyGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Capacity");

                    b.Property<TimeSpan>("Duration");

                    b.Property<string>("GroupTitle");

                    b.Property<string>("Location");

                    b.Property<string>("Objectives");

                    b.Property<int?>("OwnerId");

                    b.Property<DateTime>("StartTime");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("StudyGroups");
                });

            modelBuilder.Entity("StudyUp.Course", b =>
                {
                    b.HasOne("StudyUp.Student")
                        .WithMany("Courses")
                        .HasForeignKey("StudentId");
                });

            modelBuilder.Entity("StudyUp.Student", b =>
                {
                    b.HasOne("StudyUp.StudyGroup")
                        .WithMany("Members")
                        .HasForeignKey("StudyGroupId");
                });

            modelBuilder.Entity("StudyUp.StudyGroup", b =>
                {
                    b.HasOne("StudyUp.Student", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");
                });
#pragma warning restore 612, 618
        }
    }
}
